[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
spider = {version = "2.0.9", features = ["ua_generator", "control", "fs"] }
tokio = { version = "1.0", features = ["full"] }
scraper = "0.20.0"
serde = "1.0.209"
serde_json = "1.0.127"
